server:
  servlet:
    context-path: /gaming
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/gaming
    username: root
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
